### ISSUE TITLE
Crashes due to unsafe access to delegates and game framework classes

### ISSUE THREAD

**Issue by d11dhenderson** [DarknessFX/DFoundryFX#1]
Hello, 
We've noticed a number of places where the plugin crashes.

Win64_Test!APlayerController::GetMousePosition() Thread.cpp:265
Win64_Test!FDFX_Thread::ImGui_ImplUE_Render() 
Win64_Test!TBaseRawMethodDelegateInstance<0,FDFX_Thread,void __cdecl(AHUD *,UCanvas *),FDefaultDelegateUserPolicy>::ExecuteIfSafe() 
Win64_Test!AHUD::PostRender()

this seems to be the most prevalent we continue to get but there is another when closing the editor which occurs in FDFXThread::OnViewportClosed() line 145. 

both of our crashes seem to be because of delegates persisting longer than their depended objects do or because of expecting game framework classes to exist when they don't.

**Comment by seriema** [comment]
Very cool @DarknessFX !

Can you consider a way to turn the plugin on and off, while having the plugin enabled in a project? @d11dhenderson added a way for us in our local copy of your plugin, but there's some assumptions in the plugin code so it crashes or halts execution at various points when we disable the plugin. Perhaps there's a usecase we're missing but we'd like to be able to turn it on in any build (like on a console or whatever) to start profiling when we want to. So the enabling/disabling the plugin didn't quite fit us as a workflow.

**Comment by DarknessFX** [comment]
For sure, I want to create a Project Settings page where we can activate (or not) the plugin, this way we can also turn it off completly via .INI settings. I'm also having trouble with HighDPI, everything get mess up using Windows Display Scale 150%, it is another setting that I really want to turn on/off when needed.

I'm going to check the source, perhaps I can add this features and fixes before start the full rewrite.

**Comment by d11dhenderson** [comment]
https://github.com/DarknessFX/DFoundryFX/pull/2 I have opened a PR with our changes in it to look over as examples of places where we had errors/crashes. Our toggle command purely works on whether or not to show the UI as late init wasn't possible because of the crashes it caused mentioned earlier. Hopefully there is a better way to avoid the issues than null checks as it feels a bit messy.

**Comment by DarknessFX** [comment]
Great job @d11dhenderson, thank you guys for helping out and collaborating! 

Your change bringing ImGui inside the source (instead of a ThirdParty Lib) propably fixed a major pain that I'm having with buildings for Android.

Following your commit, I published a big update just now. Whats new:
- CVar DFoundryFX.ToggleEnabled moved to Module.
 Toggle the plugin On/Off from inside the game viewport or from the editor main frame.
 This change disconnect the plugin completely and kill the thread, when OFF the plugin don't touch the gameplay or viewport at all, toggle it ON and then a new thread, delegates, viewport hooks, etc are created.

- CVAR Stat DFoundryFX
  I added UE's Cycle_Stat to all main functions of the plugin, now with "Stat DFoundryFX" we can check exactly how much ms each function is taking. Also is a good tracking for leakings, if anything show up with COUNT bigger than 1 means some old thread/viewport hook still alive.
  
  - Fixed: Crashes when closing the Viewport or Editor.
   A new function RemoveDelegates() now is able to validate and remove any existing delegate and avoid previous crashes.
 
I'm closing this issue now, any new problem or bug with the new version (v0.97) let me know! 
Thanks!
